# yadkin - Makefile for packaging Android (best for Cygwin)
NAME = yadkin
VERSION = 0.04
PREFIX = /opt/$(NAME)
BRANCH = windows
SRCURL = yadkin.ironhead.io
HTTPSRC = http://$(SRCURL)
REPOSRC = git://$(SRCURL)
PKGSDL = SDL2-2.0.14
COMPANY = ironhead 
ORG = org.$(COMPANY).$(NAME)
TARGETS = \
	"build-tools;31.0.0" \
	"cmdline-tools;latest" \
	"platform-tools" \
	"ndk-bundle" \
	"system-images;android-31;default;x86_64"
CLITOOLS = commandlinetools-$(BRANCH).tar.gz 
JDKBIN = OpenJDK8U-jdk_x64_$(BRANCH)_hotspot_8u312b07
JDKVER = jdk8u312-b07


# main - The primary target should just unpack deps (if needed) & download everything 
main:
	test -d vendor || git clone $(REPOSRC)/yadkind.git -b $(BRANCH) --single-branch vendor
	-mkdir -p ./share/sdk/cmdline-tools/latest
	-tar -xzf vendor/$(CLITOOLS) -C share/sdk/cmdline-tools/
	-tar -xzf vendor/$(JDKBIN).tar.gz -C share/
	export JAVA_HOME=`cygpath -aw ./share/$(JDKVER)` && \
	export ANDROID_SDK_ROOT=`cygpath -aw ./share/sdk` && \
	cd share/sdk/cmdline-tools/latest/bin/ && \
		cmd /c sdkmanager.bat --verbose $(TARGETS)

# install - Install tooling
install:
	mkdir -p $(PREFIX)/bin/
	mkdir -p $(PREFIX)/etc/$(NAME)/
	mkdir -p $(PREFIX)/include/$(NAME)/
	mkdir -p $(PREFIX)/share/
	mv share $(PREFIX)/share/$(NAME)
	mkdir -p $(PREFIX)/share/$(NAME)/images/
	ln -s $(PREFIX)/share/$(NAME)/$(JDKVER)/java $(PREFIX)/bin/
	ln -s $(PREFIX)/share/$(NAME)/$(JDKVER)/keytool $(PREFIX)/bin/
	ln -s $(PREFIX)/share/$(NAME)/sdk/platform-tools/adb $(PREFIX)/bin/
	ln -s $(PREFIX)/share/$(NAME)/sdk/emulator/emulator $(PREFIX)/bin/
	test -d /etc/profile.d/ || mkdir -p /etc/profile.d/
	cp environment/cygwin.env /etc/profile.d/$(NAME).sh
	echo "$(NAME) installed successfully, please restart your terminal or system for PATH changes to take effect."


# android-device - Build a new Android device
#	export JAVA_HOME=./share/$(JDKVER) &&
#	export ANDROID_SDK_ROOT=./share/sdk &&
#			-p /opt/yadkin/share/images
#		-k "system-images;android-28;google_apis;x86_64"
#android-device:
#	cmd /c avdmanager.bat create avd \
#		-n ironhead_test \
#		-k "system-images;android-31;google_apis;x86_64" \
#		-p `cygpath -w $(PREFIX)/share/images`

# image - Build a new Android device
image:
	cmd /c avdmanager.bat --verbose create avd \
		--force -d 18 -n yadkin_pixel_3 \
		-k "system-images;android-31;default;x86_64" \
		-p `cygpath -w $(PREFIX)/share/images`

# image - Build a new Android device
image-list:
	cmd /c avdmanager.bat list avd

# image-list-available - Build a new Android device
image-list-available:
	cmd /c avdmanager.bat list

# image-help - Build a new Android device
image-help:
	cmd /c avdmanager.bat create avd --help 

# image-start - Start an image
image-start:
	cmd /c
	
#		./share/sdk/cmdline-tools/latest/bin/sdkmanager --list $(TARGETS)

# sdl-deps - Just unpack SDL and friends
sdl-deps:
	-tar -xzf vendor/$(PKGSDL).tar.gz -C build/SDL

# explain - List all the targets and what they do
explain:
	@sed -n '/^#/p' Makefile | sed 's/# //' | \
		awk -F - '{ printf "%-12s %s\n", $$1, $$2 }'

# android-app - Create an android app somewhere
android-app:
	printf ''

# cli - Build a CLI to make apps and whatnot...
cli:	
	printf ''

# clean - Remove dependencies
clean:
	rm -rf share/

# docs - Create index.html
docs:
	markdown -S README.md > docs/index.html

.PHONY: build docs
